project:
  type: book

book:
  title: "PanRocq"
  author: "Florent Schaffhauser"
  date: "15/09/2026"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



